AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Account-agnostic CloudFormation stack to detect AWS Secrets Manager
  rotations/updates and notify teams via SNS.
  - Hourly schedule
  - Metadata-only (no secret values)
  - Silent unless changes detected
  - GovCloud compatible
  - No console drift

############################################
# PARAMETERS
############################################
Parameters:

  SystemName:
    Type: String
    Description: Logical system or platform name (e.g. mihub, cdw, koios)

  Environment:
    Type: String
    AllowedValues: [sandbox, dev, int, staging, uat, prod]
    Description: Logical environment label used in alerts and naming

  AlertEmail:
    Type: String
    Description: Primary email address for SNS notifications

  AlertEmail2Optional:
    Type: String
    Default: ""
    Description: Optional secondary email address for SNS notifications

############################################
# CONDITIONS
############################################
Conditions:
  HasSecondAlertEmail: !Not [!Equals [!Ref AlertEmail2Optional, ""]]

############################################
# RESOURCES
############################################
Resources:

  ##########################################
  # SNS TOPIC
  ##########################################
  SecretRotationAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub secret-rotation-alerts-${SystemName}-${Environment}

  ##########################################
  # SNS SUBSCRIPTIONS
  ##########################################
  PrimaryAlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SecretRotationAlertsTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  SecondaryAlertSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasSecondAlertEmail
    Properties:
      TopicArn: !Ref SecretRotationAlertsTopic
      Protocol: email
      Endpoint: !Ref AlertEmail2Optional

  ##########################################
  # IAM ROLE (LEAST PRIVILEGE)
  ##########################################
  SecretRotationMonitorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub secret-rotation-monitor-${SystemName}-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: secret-rotation-monitor-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              # Secrets Manager metadata only
              - Effect: Allow
                Action:
                  - secretsmanager:ListSecrets
                  - secretsmanager:DescribeSecret
                Resource: "*"

              # Publish notifications
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref SecretRotationAlertsTopic

              # CloudWatch logging
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ##########################################
  # LAMBDA FUNCTION (INLINE CODE)
  ##########################################
  DetectSecretRotationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub detect-secret-rotation-${SystemName}-${Environment}
      Runtime: python3.13
      Handler: index.lambda_handler
      Role: !GetAtt SecretRotationMonitorRole.Arn
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          SYSTEM_NAME: !Ref SystemName
          ENVIRONMENT: !Ref Environment
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
          SNS_TOPIC_ARN: !Ref SecretRotationAlertsTopic
      Code:
        ZipFile: |
          import boto3
          import os
          from datetime import datetime, timezone, timedelta
          from zoneinfo import ZoneInfo
          from botocore.exceptions import ClientError

          SYSTEM_NAME = os.environ["SYSTEM_NAME"]
          ENVIRONMENT = os.environ["ENVIRONMENT"]
          ACCOUNT_ID = os.environ["AWS_ACCOUNT_ID"]
          SNS_TOPIC_ARN = os.environ["SNS_TOPIC_ARN"]

          REGION = boto3.session.Session().region_name

          secrets = boto3.client("secretsmanager")
          sns = boto3.client("sns")

          eastern_tz = ZoneInfo("America/New_York")

          def lambda_handler(event, context):
              now_utc = datetime.now(timezone.utc)
              window_start = now_utc - timedelta(hours=1)

              findings = []

              paginator = secrets.get_paginator("list_secrets")

              for page in paginator.paginate():
                  for secret in page.get("SecretList", []):
                      name = secret["Name"]

                      try:
                          meta = secrets.describe_secret(SecretId=name)
                      except ClientError:
                          continue

                      changed_utc = meta.get("LastChangedDate", meta["CreatedDate"])

                      if changed_utc < window_start:
                          continue

                      findings.append({
                          "name": name,
                          "arn": meta["ARN"],
                          "changed_utc": changed_utc
                      })

              if not findings:
                  return {
                      "secrets_changed": 0
                  }

              findings.sort(key=lambda x: x["changed_utc"], reverse=True)

              body = (
                  f"System: {SYSTEM_NAME}\n"
                  f"Environment: {ENVIRONMENT}\n"
                  f"AWS Account ID: {ACCOUNT_ID}\n"
                  f"AWS Region: {REGION}\n"
                  f"Detection Window: last 1 hour\n\n"
                  f"Secrets Changed ({len(findings)}):\n\n"
              )

              for idx, item in enumerate(findings, start=1):
                  et_time = item["changed_utc"].astimezone(eastern_tz)
                  body += (
                      f"{idx}) Secret Name: {item['name']}\n"
                      f"   ARN: {item['arn']}\n"
                      f"   Last Changed (ET): {et_time.strftime('%Y-%m-%d %H:%M:%S %Z')}\n\n"
                  )

              sns.publish(
                  TopicArn=SNS_TOPIC_ARN,
                  Subject=f"Secret Rotation Detected – {SYSTEM_NAME}-{ENVIRONMENT}",
                  Message=body
              )

              return {
                  "secrets_changed": len(findings)
              }

  ##########################################
  # EVENTBRIDGE SCHEDULER (HOURLY)
  ##########################################
  SecretRotationSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub secret-rotation-hourly-${SystemName}-${Environment}
      Description: Hourly Secrets Manager rotation detection
      ScheduleExpression: rate(1 hour)
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt DetectSecretRotationLambda.Arn
        RoleArn: !GetAtt SecretRotationMonitorRole.Arn
        Input: "{}"
